name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm@9.12.2

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Frontend
        run: pnpm run build --filter=frontend
