apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaverse-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metaverse-frontend
  template:
    metadata:
      labels:
        app: metaverse-frontend
    spec:
      containers:
      - name: metaverse-frontend
        image: kartiktoogoated/metaverse-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"  # Minimum amount of memory the container will get
            cpu: "500m"      # Minimum amount of CPU the container will get
          limits:
            memory: "1Gi"    # Maximum amount of memory the container can use
            cpu: "1000m"     # Maximum amount of CPU the container can use

---
apiVersion: v1
kind: Service
metadata:
  name: metaverse-frontend
spec:
  selector:
    app: metaverse-frontend  # This should match the labels from the Deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose the service on
      targetPort: 3000  # Port on which your container is running
  type: ClusterIP  # Change to NodePort if you want external access
