apiVersion: v1
kind: Service
metadata:
  name: metaverse-frontend
spec:
  selector:
    app: metaverse-frontend  # This should match the labels from the Deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose the service on
      targetPort: 3000  # Port on which your container is running
  type: ClusterIP  # Change to NodePort if you want external access
